name: flutter_emoji_feedback
description: A fully customizable widget to receive feedback from your users. Can be used to get user's mood or evaluate experience (and more !)
version: 0.2.0
homepage: https://github.com/stevenosse/flutter_emoji_feedback

environment:
  sdk: '>3.1.5'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  assets:
    - assets/
